presets:
  tv:
    transmission:
      host: localhost
      port: 9091
      removewhendone: True
    exists_series: /mnt/extstorage/downloads/
    series:
      - The Big Bang Theory
      - The Game of Thrones
      - American Dad
      - Family Guy
email:
  from: ddarkheart@gmail.com
  to: diego@diegoram.me
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_username: 'xxxxxx'
  smtp_password: 'xxxxxxx'
  smtp_tls: yes
  template: accepted

tasks:

  showrss:
    rss: http://showrss.karmorra.info/feeds/all.rss
    preset: tv

  rb-chat:
    rss: http://rss.bt-chat.com/?group=3
    preset: tv

  rlslog_dvdrips:
    rlslog: http://www.rlslog.net/category/movies/dvdrip/
    imdb:
      min_score: 4.5
      min_votes: 1000
      min_year: 2010
      reject_genres:
        - documentary
        - musical
        - music
        - biography
        - romance
    transmission:
      host: localhost
      port: 9091
