templates:
  tv:
    transmission:
      host: localhost
      port: 9091
    exists_series: /media/hd/downloads/
    series:
      - The Big Bang Theory
      - Game of Thrones
      - Hannibal
      - 24
      - The Walking Dead
      - True Detective
email:
  from: ddarkheart@gmail.com
  to: diego@diegoram.me
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_username: 'XXXX'
  smtp_password: 'XXXXX'
  smtp_tls: yes
  template: accepted

tasks:

  rb-chat:
    rss: http://rss.bt-chat.com/?group=3
    template: tv
  torrentz:
    rss: http://torrentz.eu/feed
    template: tv
  extratorrent:
    rss: http://extratorrent.cc/rss.xml?cid=8
    template: tv
  feedburner:
    rss: http://feeds.feedburner.com/eztv-rss-atom-feeds?format=xml
    template: tv
  rlslog_dvdrips:
    rlslog: http://www.rlslog.net/category/movies/dvdrip/
    imdb:
      min_score: 4.5
      min_votes: 1000
      min_year: 2010
      reject_genres:
        - documentary
        - musical
        - music
        - biography
        - romance
    transmission:
      host: localhost
      port: 9091

  subtitles:
    find:
      path: 
        - /media/hd/downloads/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    periscope:
      languages:
        - es
      alternatives:
        - en
      overwrite: yes
